#t:621-768 ; rate:335-697 ; loss_0.0-0.0 ; delay:0-0
import os
import time
def link():
	tracef = open("traces/random/trace292.txt", 'w')
	tracef.close()
	tracef = open("traces/random/trace292.txt", 'a+')
	tracef.write(f"643 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc add dev lo root netem rate 643kbit")
	time.sleep(0.701)
	tracef.write(f"446 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 446kbit")
	time.sleep(0.677)
	tracef.write(f"341 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 341kbit")
	time.sleep(0.713)
	tracef.write(f"409 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 409kbit")
	time.sleep(0.754)
	tracef.write(f"669 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 669kbit")
	time.sleep(0.652)
	tracef.write(f"355 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 355kbit")
	time.sleep(0.756)
	tracef.write(f"603 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 603kbit")
	time.sleep(0.625)
	tracef.write(f"530 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 530kbit")
	time.sleep(0.696)
	tracef.write(f"530 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 530kbit")
	time.sleep(0.678)
	tracef.write(f"499 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 499kbit")
	time.sleep(0.669)
	tracef.write(f"351 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 351kbit")
	time.sleep(0.669)
	tracef.write(f"372 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 372kbit")
	time.sleep(0.633)
	tracef.write(f"558 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 558kbit")
	time.sleep(0.68)
	tracef.write(f"425 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 425kbit")
	time.sleep(0.633)
	tracef.write(f"674 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 674kbit")
	time.sleep(0.734)
	tracef.write(f"577 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 577kbit")
	time.sleep(0.687)
	tracef.write(f"423 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 423kbit")
	time.sleep(0.638)
	tracef.write(f"488 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 488kbit")
	time.sleep(0.625)
	tracef.write(f"365 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 365kbit")
	time.sleep(0.707)
	tracef.write(f"451 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 451kbit")
	time.sleep(0.744)
	tracef.write(f"680 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 680kbit")
	time.sleep(0.691)
	tracef.write(f"663 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 663kbit")
	time.sleep(0.643)
	tracef.write(f"654 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 654kbit")
	time.sleep(0.687)
	tracef.write(f"648 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 648kbit")
	time.sleep(0.725)
	tracef.write(f"385 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 385kbit")
	time.sleep(0.627)
	tracef.write(f"514 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 514kbit")
	time.sleep(0.631)
	tracef.write(f"513 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 513kbit")
	time.sleep(0.763)
	tracef.write(f"676 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 676kbit")
	time.sleep(0.701)
	tracef.write(f"594 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 594kbit")
	time.sleep(0.723)
	tracef.write(f"466 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 466kbit")
	time.sleep(0.707)
	tracef.write(f"390 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 390kbit")
	time.sleep(0.749)
	tracef.write(f"401 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 401kbit")
	time.sleep(0.716)
	tracef.write(f"519 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 519kbit")
	time.sleep(0.761)
	tracef.write(f"595 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 595kbit")
	time.sleep(0.765)
	tracef.write(f"555 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 555kbit")
	time.sleep(0.64)
	tracef.write(f"689 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 689kbit")
	time.sleep(0.634)
	tracef.write(f"371 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 371kbit")
	time.sleep(0.624)
	tracef.write(f"479 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 479kbit")
	time.sleep(0.723)
	tracef.write(f"433 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 433kbit")
	time.sleep(0.654)
	tracef.write(f"668 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 668kbit")
	time.sleep(0.663)
	tracef.write(f"653 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 653kbit")
	time.sleep(0.644)
	tracef.write(f"603 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 603kbit")
	time.sleep(0.651)
	tracef.write(f"449 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 449kbit")
	time.sleep(0.638)
	tracef.write(f"403 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 403kbit")
	time.sleep(0.654)
	tracef.write(f"335 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 335kbit")
	time.sleep(0.705)
	tracef.write(f"547 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 547kbit")
	time.sleep(0.734)
	tracef.write(f"631 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 631kbit")
	time.sleep(0.704)
	tracef.write(f"498 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 498kbit")
	time.sleep(0.756)
	tracef.write(f"672 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 672kbit")
	time.sleep(0.65)
	tracef.write(f"584 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 584kbit")
	time.sleep(0.627)
	tracef.write(f"439 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 439kbit")
	time.sleep(0.735)
	tracef.write(f"473 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 473kbit")
	time.sleep(0.648)
	tracef.write(f"588 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 588kbit")
	time.sleep(0.704)
	tracef.write(f"526 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 526kbit")
	time.sleep(0.719)
	tracef.write(f"555 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 555kbit")
	time.sleep(0.626)
	tracef.write(f"463 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 463kbit")
	time.sleep(0.643)
	tracef.write(f"566 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 566kbit")
	time.sleep(0.652)
	tracef.write(f"408 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 408kbit")
	time.sleep(0.723)
	tracef.write(f"580 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 580kbit")
	time.sleep(0.712)
	tracef.write(f"657 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 657kbit")
	time.sleep(0.621)
	tracef.write(f"535 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 535kbit")
	time.sleep(0.624)
	tracef.write(f"380 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 380kbit")
	time.sleep(0.725)
	tracef.write(f"655 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 655kbit")
	time.sleep(0.678)
	tracef.write(f"353 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 353kbit")
	time.sleep(0.661)
	tracef.write(f"447 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 447kbit")
	time.sleep(0.647)
	tracef.write(f"507 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 507kbit")
	time.sleep(0.76)
	tracef.write(f"403 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 403kbit")
	time.sleep(0.655)
	tracef.write(f"559 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 559kbit")
	time.sleep(0.685)
	tracef.write(f"431 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 431kbit")
	time.sleep(0.628)
	tracef.write(f"548 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 548kbit")
	time.sleep(0.664)
	tracef.write(f"455 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 455kbit")
	time.sleep(0.686)
	tracef.write(f"451 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 451kbit")
	time.sleep(0.682)
	tracef.write(f"364 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 364kbit")
	time.sleep(0.627)
	tracef.write(f"658 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 658kbit")
	time.sleep(0.689)
	tracef.write(f"357 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 357kbit")
	time.sleep(0.629)
	tracef.write(f"497 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 497kbit")
	time.sleep(0.724)
	tracef.write(f"498 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 498kbit")
	time.sleep(0.748)
	tracef.write(f"488 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 488kbit")
	time.sleep(0.694)
	tracef.write(f"420 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 420kbit")
	time.sleep(0.714)
	tracef.write(f"472 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 472kbit")
	time.sleep(0.757)
	tracef.write(f"580 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 580kbit")
	time.sleep(0.659)
	tracef.write(f"485 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 485kbit")
	time.sleep(0.73)
	tracef.write(f"680 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 680kbit")
	time.sleep(0.751)
	tracef.write(f"444 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 444kbit")
	time.sleep(0.733)
	tracef.write(f"384 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 384kbit")
	time.sleep(0.763)
	tracef.write(f"477 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 477kbit")
	time.sleep(0.678)
	tracef.write(f"417 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 417kbit")
	time.sleep(0.726)
	tracef.write(f"608 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 608kbit")
	time.sleep(0.631)
	tracef.write(f"418 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 418kbit")
	time.sleep(0.625)
	tracef.write(f"622 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 622kbit")
	time.sleep(0.626)
	tracef.write(f"642 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 642kbit")
	time.sleep(0.728)
	tracef.write(f"413 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 413kbit")
	time.sleep(0.7)
	tracef.write(f"630 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 630kbit")
	time.sleep(0.648)
	tracef.write(f"652 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 652kbit")
	time.sleep(0.663)
	tracef.write(f"651 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 651kbit")
	time.sleep(0.737)
	tracef.write(f"668 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 668kbit")
	time.sleep(0.665)
	tracef.write(f"398 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 398kbit")
	time.sleep(0.76)
	tracef.write(f"376 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 376kbit")
	time.sleep(0.711)
	tracef.write(f"670 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 670kbit")
	time.sleep(0.634)
	tracef.write(f"490 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 490kbit")
	time.sleep(0.647)
	tracef.write(f"611 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 611kbit")
	time.sleep(0.761)
	tracef.write(f"673 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 673kbit")
	time.sleep(0.648)
	tracef.write(f"394 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 394kbit")
	time.sleep(0.645)
	tracef.write(f"407 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 407kbit")
	time.sleep(0.761)
	tracef.write(f"572 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 572kbit")
	time.sleep(0.661)
	tracef.write(f"526 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 526kbit")
	time.sleep(0.627)
	tracef.write(f"445 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 445kbit")
	time.sleep(0.762)
	tracef.write(f"335 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 335kbit")
	time.sleep(0.629)
	tracef.write(f"671 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 671kbit")
	time.sleep(0.737)
	tracef.write(f"407 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 407kbit")
	time.sleep(0.698)
	tracef.write(f"536 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 536kbit")
	time.sleep(0.654)
	tracef.write(f"593 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 593kbit")
	time.sleep(0.726)
	tracef.write(f"636 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 636kbit")
	time.sleep(0.724)
	tracef.write(f"478 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 478kbit")
	time.sleep(0.659)
	tracef.write(f"411 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 411kbit")
	time.sleep(0.626)
	tracef.write(f"437 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 437kbit")
	time.sleep(0.649)
	tracef.write(f"664 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 664kbit")
	time.sleep(0.67)
	tracef.write(f"501 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 501kbit")
	time.sleep(0.743)
	tracef.write(f"547 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 547kbit")
	time.sleep(0.699)
	tracef.write(f"531 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 531kbit")
	time.sleep(0.626)
	tracef.write(f"478 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 478kbit")
	time.sleep(0.734)
	tracef.write(f"534 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 534kbit")
	time.sleep(0.657)
	tracef.write(f"376 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 376kbit")
	time.sleep(0.676)
	tracef.write(f"623 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 623kbit")
	time.sleep(0.679)
	tracef.write(f"569 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 569kbit")
	time.sleep(0.719)
	tracef.write(f"560 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 560kbit")
	time.sleep(0.622)
	tracef.write(f"365 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 365kbit")
	time.sleep(0.671)
	tracef.write(f"685 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 685kbit")
	time.sleep(0.744)
	tracef.write(f"493 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 493kbit")
	time.sleep(0.705)
	tracef.write(f"605 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 605kbit")
	time.sleep(0.714)
	tracef.write(f"413 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 413kbit")
	time.sleep(0.714)
	tracef.write(f"553 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 553kbit")
	time.sleep(0.651)
	tracef.write(f"359 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 359kbit")
	time.sleep(0.622)
	tracef.write(f"602 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 602kbit")
	time.sleep(0.755)
	tracef.write(f"361 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 361kbit")
	time.sleep(0.752)
	tracef.write(f"402 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 402kbit")
	time.sleep(0.656)
	tracef.write(f"516 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 516kbit")
	time.sleep(0.706)
	tracef.write(f"585 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 585kbit")
	time.sleep(0.748)
	tracef.write(f"420 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 420kbit")
	time.sleep(0.709)
	tracef.write(f"359 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 359kbit")
	time.sleep(0.638)
	tracef.write(f"385 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 385kbit")
	time.sleep(0.706)
	tracef.write(f"508 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 508kbit")
	time.sleep(0.697)
	tracef.write(f"384 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 384kbit")
	time.sleep(0.766)
	tracef.write(f"599 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 599kbit")
	time.sleep(0.709)
	tracef.write(f"566 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 566kbit")
	time.sleep(0.622)
	tracef.write(f"448 ; {round(time.time() * 1000)}\n")
	os.system("echo 1 | sudo -S tc qdisc change dev lo root netem rate 448kbit")
	time.sleep(0.727)
	os.system("echo 1 | sudo -S tc qdisc del dev lo root")
	tracef.close()
def main():
	link()
if __name__ == "__main__":
	main()